services:
  - type: web
    name: whatsapp-webhook
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --workers=2 --threads=4 --timeout=120 --bind 0.0.0.0:$PORT"
    envVars:
      - key: WHATSAPP_TOKEN
        sync: false
      - key: WHATSAPP_PHONE_ID
        sync: false
      - key: VERIFY_TOKEN
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
    healthCheckPath: /health
